# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: test_mts_camels_ar_128

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: 128_basin_list.txt
validation_basin_file: 128_basin_list.txt
test_basin_file: 128_basin_list.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: "01/01/2008"
train_end_date: "01/01/2016"
validation_start_date: "01/01/2016"
validation_end_date: "01/01/2020"
test_start_date: "01/01/2020"
test_end_date: "01/01/2024"

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu, mps or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 8

# specify how many random basins to use for validation
validate_n_random_basins: 32

# specify which metrics to calculate during validation (see neuralhydrology.evaluation.metrics)
# this can either be a list or a dictionary. If a dictionary is used, the inner keys must match the name of the
# target_variable specified below. Using dicts allows for different metrics per target variable.
metrics:
  - NSE
  - KGE
  - PI

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, mtslstm]
# (has to match the if statement in modelzoo/__init__.py)
model: arlstm

# define whether the MTS-LSTM's state transfer layer uses an
# identity or linear operation for hidden (h) and cell state (c).
transfer_mtslstm_states:
  h: linear
  c: linear

# prediction head [regression]. Define the head specific parameters below
head: regression

# ----> Regression settings <----
output_activation: linear

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 64

# Initial bias value of the forget gate
initial_forget_bias: 3

allow_subsequent_nan_losses: 8

# Dropout applied to the output of the LSTM
output_dropout: 0.4

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam]
optimizer: Adam

# specify loss [MSE, NSE, RMSE]
loss: NSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
  0: 5e-4
  10: 1e-4
  25: 5e-5

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 128

# If a value, clips the gradients during training to that norm.
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length.
# If use_frequencies is used, this needs to be a dict mapping each frequency to a predict_last_n-value, else an int.
predict_last_n: 1

# Length of the input sequence
# If use_frequencies is used, this needs to be a dict mapping each frequency to a seq_length, else an int.
seq_length: 48

# Number of parallel workers used in the data pipeline
num_workers: 12

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# If a value and greater than 0, logs n random basins as figures during validation
log_n_figures: 8

# Save model weights every n epochs
save_weights_every: 1

# --- Data configurations --------------------------------------------------------------------------

# which data set to use [camels_us, camels_gb, global, hourly_camels_us]
dataset: hourly_camels_usto

# Path to CAMELS data set
data_dir: F:\Data\LSH\CAMELS_US_TORONTO

# Forcing product [daymet, maurer, maurer_extended, nldas, nldas_extended, nldas_hourly]
# can be either a list of forcings or a single forcing product
forcings:
  - nldas_hourly

dynamic_inputs:
  - total_precipitation
  - temperature
  - pressure

# which columns to use as target
target_variables:
  - qobs_mm_per_hour

# clip negative predictions to zero for all variables listed below. Should be a list, even for single variables.
clip_targets_to_zero:
  - qobs_mm_per_hour

autoregressive_inputs:
  - qobs_mm_per_hour_shift6

lagged_features:
  qobs_mm_per_hour:
   - 6

use_basin_id_encoding: True

static_attributes:
  - frac_forest
  - high_q_freq
  - high_prec_dur
  - low_prec_freq
  - area_gages2
  - low_prec_dur
  - pet_mean
  - elev_mean
  - high_prec_freq
  - zero_q_freq
  - p_mean
  - gauge_lon
  - q_mean
  - q95
  - slope_mean
  - low_q_dur
  - runoff_ratio
  - frac_snow
  - q5
  - gauge_lat
  - aridity
  - p_seasonality
  - high_q_dur